### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [ZoeOstapiuk/Kottans#2]
Pass `"50000000000006114"` to `GetCreditCardVendor` method
Expected result: "Unknown" (because number is invalid)
Actual result: "Maestro"

**Comment by ZoeOstapiuk** [comment]
Fixed #2

**Comment by intrueder** [comment]
Still reproducable for `35301113333000001`
Expected result: "Unknown" (because 17 digits - invalid length for JCB)
Actual result: "JCB"

**Comment by ZoeOstapiuk** [comment]
Fixed #2 once more, also fixed method generating next valid card number.
